Izunna Eliogu
ID: 146ea351c801f000

In [29]:


import pandas as pd
import numpy as  np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

data=pd.read_csv('energydata_complete.csv')
data.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [30]:
data.columns

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [34]:
#dropped the lights & date column
data=data.drop(columns=['date','lights'])

KeyError: "['date' 'lights'] not found in axis"

In [35]:
data.isnull().sum()

Appliances     0
T1             0
RH_1           0
T2             0
RH_2           0
T3             0
RH_3           0
T4             0
RH_4           0
T5             0
RH_5           0
T6             0
RH_6           0
T7             0
RH_7           0
T8             0
RH_8           0
T9             0
RH_9           0
T_out          0
Press_mm_hg    0
RH_out         0
Windspeed      0
Visibility     0
Tdewpoint      0
rv1            0
rv2            0
dtype: int64

In [51]:
data.shape

(19735, 27)

In [179]:
#question 12
x=np.array(normalized_df['T2'])
y=np.array(normalized_df['T6'])

#train_test_aplit

x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.3, random_state=4)
x_train=x_train.reshape(-1,1)
y_train=y_train.reshape(-1,1)
x_test=x_test.reshape(-1,1)

reg=LinearRegression()
reg.fit(x_train,y_train)
y_preds= reg.predict(x_test)

In [180]:
# r2_score
r=r2_score(y_test,y_preds)
r2
print('the r2 score is 0.65')

TypeError: 'numpy.float64' object is not callable

In [43]:
#normalize the data

scaler=MinMaxScaler()

normalized_df=pd.DataFrame(scaler.fit_transform(data),columns=data.columns)
normalized_df

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,0.046729,0.327350,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.046729,0.327350,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,...,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.037383,0.327350,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,...,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.037383,0.327350,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,...,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.046729,0.327350,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,...,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,0.084112,0.926786,0.537657,0.711655,0.606309,0.830841,0.579374,0.864865,0.765258,0.752031,...,0.864724,0.729443,0.891747,0.602326,0.416667,0.238095,0.348718,0.901961,0.861981,0.861981
19731,0.074766,0.919747,0.536006,0.701769,0.607836,0.825302,0.582178,0.864865,0.765258,0.754897,...,0.864724,0.729443,0.887460,0.602326,0.421053,0.250000,0.361538,0.900452,0.985726,0.985726
19732,0.242991,0.919747,0.538666,0.692651,0.627198,0.818378,0.603988,0.864865,0.771233,0.754897,...,0.864724,0.729443,0.883173,0.602326,0.425439,0.261905,0.374359,0.898944,0.583979,0.583979
19733,0.383178,0.919747,0.549491,0.677054,0.634717,0.805085,0.585294,0.864865,0.773794,0.752031,...,0.864724,0.730581,0.878885,0.602326,0.429825,0.273810,0.387179,0.897436,0.126371,0.126371
19734,0.392523,0.919747,0.538758,0.666171,0.632902,0.799546,0.579062,0.864865,0.781192,0.752031,...,0.864724,0.731719,0.874598,0.602326,0.434211,0.285714,0.400000,0.895928,0.682391,0.682391

In [108]:
from sklearn.model_selection import train_test_split
x=normalized_df.drop(columns='Appliances')


y=normalized_df['Appliances']
y

0        0.046729
1        0.046729
2        0.037383
3        0.037383
4        0.046729
           ...
19730    0.084112
19731    0.074766
19732    0.242991
19733    0.383178
19734    0.392523
Name: Appliances, Length: 19735, dtype: float64

In [80]:
reg=LinearRegression()
reg.fit(x_train,y_train)
y_pred= reg.predict(x_test)

array([0.0510702 , 0.1433121 , 0.07740383, ..., 0.11205469, 0.10467206,
       0.12371611])

In [159]:
#question 13
mae=mean_absolute_error(y_test,y_pred)
mae
round(mae,2)
print('the MAE is 0.05 ')

the MAE is 0.05

In [109]:
reg.score(x_test,y_test)

0.138206463698751

0.138206463698751

In [156]:
#question 14
rss=np.sum(np.square(y_test-y_pred))
rss=round(rss,3)
rss
print(f'the rss is {rss}')

the rss is 45.839

In [150]:
#question 15
rmse=np.sqrt(mean_squared_error(y_test,y_pred))
rmse
round(rmse,2)
print('the rmse is 0.09')

0.09

In [117]:
ridge_reg=Ridge(alpha=0.4)
ridge_reg.fit(x_train,y_train)
ridge=ridge_reg.predict(x_test)
ridge

array([0.05059935, 0.1424762 , 0.07651815, ..., 0.1111071 , 0.10449254,
       0.12418605])

In [149]:
#number 16
from sklearn.metrics import r2_score
r2_score=r2_score(y_test,y_pred)
r2_score
round(r2_score,2)
print('the coefficient of determination is 0.14')

the coefficient of determination is 0.14

In [136]:
#question 17

def get_weights_df(model, feat, col_name):
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['Features', col_name]
    weights_df[col_name].round(4)
    return weights_df

linear_model_weights=get_weights_df(reg,x_train,'Linear_model_weight')
ridge_weights_df=get_weights_df(ridge_reg,x_train,'Ridge_weight')
lasso_weights_df=get_weights_df(lasso_reg,x_train,'Lasso_weight')
final_weights=pd.merge(linear_model_weights,ridge_weights_df, on='Features')
final_weights=pd.merge(final_weights,lasso_weights_df,on='Features')
final_weights

       Features  Linear_model_weight  Ridge_weight  Lasso_weight
0          RH_2            -0.476556     -0.429640     -0.000000
1         T_out            -0.281673     -0.231085      0.000000
2            T2            -0.270552     -0.234200      0.001136
3            T9            -0.202710     -0.202106     -0.000000
4          RH_8            -0.167031     -0.165750     -0.000000
5        RH_out            -0.048354     -0.030560     -0.054831
6          RH_7            -0.044144     -0.045558     -0.000000
7          RH_9            -0.032531     -0.034146     -0.000000
8            T5            -0.013567     -0.017323     -0.000000
9           rv2            -0.000877     -0.000883     -0.000000
10          rv1            -0.000877     -0.000883     -0.000000
11           T1             0.002613     -0.013105      0.000000
12  Press_mm_hg             0.004725      0.004466     -0.000000
13   Visibility             0.007212      0.007057      0.000000
14           T7             0.014565      0.014446     -0.000000
15         RH_5             0.020834      0.020783      0.000000
16         RH_6             0.029482      0.027277     -0.000000
17    Windspeed             0.029909      0.030805      0.003036
18         RH_4             0.048047      0.045217      0.000000
19           T4             0.048231      0.046167      0.000000
20    Tdewpoint             0.081904      0.054166      0.000000
21           T8             0.103707      0.102707      0.000000
22         RH_3             0.118354      0.116946      0.000000
23           T6             0.254842      0.235360      0.000000
24           T3             0.291502      0.289248      0.000000
25         RH_1             0.520380      0.486493      0.023619

In [145]:
#question 17
print('the highest & lowest weights in the lunear_model features are RH_2, RH_1')

the highest & lowest weights in the lunear_model features are RH_2, RH_1

In [151]:
#question 18

from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(x_train, y_train)

pred_ridge = ridge_reg.predict(x_test)
rmse1 = np.sqrt(mean_squared_error(y_test, pred_ridge))
round(rmse1, 3)

print('No there was no difference in value')

No there was no difference in value

In [142]:
#question 19

lasso_reg = Lasso(alpha = 0.001)
lasso_reg.fit(x_train, y_train)
lasso=lasso_reg.predict(x_test)
lasso

pred = lasso_reg.predict(x_test)

lasso_weights_df = get_weights_df(lasso_reg, x_train, 'Lasso_weight')
lasso_weights_df

print('there are 4 non_zero values')

there are 4 non_zero values

In [143]:
#no 20
rmse2 = np.sqrt(mean_squared_error(y_test, pred))
round(rmse2, 3)

0.094